In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('../My_Datas/Data/Groceries.xlsx')

In [10]:
df.sort_values('Price_Dollars', ascending=False)

,Product_ID,Category,Item,Price_Dollars,Inventory,Last_Updated,Next_Scheduled_Shipment
23,P100033,Frozen: Frozen Fruit,Frozen Blueberries,10.99,162,2023-05-28 22:14:00,2023-06-28
11,P100021,Produce: Meat,Chicken (Organic),10.49,284,2023-06-13 07:20:00,2023-06-17
10,P100020,Produce: Meat,Beef,8.99,145,2023-06-13 07:00:00,2023-06-17
12,P100022,Produce: Meat,Turkey,7.99,188,2023-06-13 07:32:00,2023-06-17
24,P100034,Frozen: Frozen Fruit,Frozen Pineapple,7.96,178,2023-05-28 22:11:00,2023-06-28
21,P100031,Frozen: Frozen Snacks,Chicken Nuggets,6.99,85,2023-05-28 22:02:00,2023-06-28
5,P100015,Produce: Fruit,Watermelon,5.99,99,2023-06-12 19:15:00,2023-06-15
19,P100029,Pantry: Snacks,Cookies (Oatmeal),5.39,340,2023-06-10 12:24:00,2023-06-24
22,P100032,Frozen: Frozen Snacks,Spinach Dip,4.96,76,2023-05-28 22:05:00,2023-06-28
15,P100025,Produce: Dairy,Milk (Soy),4.49,32,2023-06-13 08:37:00,2023-06-17
2,P100012,Produce: Fruit,Grapes,4.00,200,2023-06-12 17:22:00,2023-06-15
4,P100014,Produce: Fruit,Organic Strawberries,3.99,148,2023-06-12 18:10:00,2023-06-15
13,P100023,Produce: Dairy,Butter,3.50,400,2023-06-13 08:35:00,2023-06-17
14,P100024,Produce: Dairy,Eggs,3.29,234,2023-06-13 08:54:00,2023-06-17
20,P100030,Pantry: Snacks,Raisins,2.99,5,2023-06-10 12:38:00,2023-06-24
18,P100028,Pantry: Snacks,Chips,2.50,365,2023-06-10 12:12:00,2023-06-24
7,P100017,Produce: Vegetable,Carrots,2.00,200,2023-06-12 18:05:00,2023-06-15
8,P100018,Produce: Vegetable,Celery,1.99,50,2023-06-12 16:42:00,2023-06-15
6,P100016,Produce: Vegetable,Cabbage,1.78,78,2023-06-12 19:25:00,2023-06-15
17,P100027,Pantry: Snacks,Apple Sauce - organic,1.50,27,2023-06-10 12:02:00,2023-06-24
0,P100010,Produce: Fruit,Apple,1.50,349,2023-06-12 15:35:00,2023-06-15
16,P100026,Produce: Dairy,Yogurt,1.00,432,2023-06-13 08:41:00,2023-06-17
3,P100013,Produce: Fruit,Grapefruit,0.99,50,2023-06-12 16:29:00,2023-06-15
9,P100019,Produce: Vegetable,Cucumber,0.99,230,2023-06-12 17:47:00,2023-06-15
1,P100011,Produce: Fruit,Banana,0.40,500,2023-06-12 18:30:00,2023-06-15

In [3]:
df.head()

,Product_ID,Category,Item,Price_Dollars,Inventory,Last_Updated,Next_Scheduled_Shipment
0,P100010,Produce: Fruit,Apple,1.50,349,2023-06-12 15:35:00,2023-06-15
1,P100011,Produce: Fruit,Banana,0.40,500,2023-06-12 18:30:00,2023-06-15
2,P100012,Produce: Fruit,Grapes,4.00,200,2023-06-12 17:22:00,2023-06-15
3,P100013,Produce: Fruit,Grapefruit,0.99,50,2023-06-12 16:29:00,2023-06-15
4,P100014,Produce: Fruit,Organic Strawberries,3.99,148,2023-06-12 18:10:00,2023-06-15

In [4]:
df.groupby("Category")["Inventory"].sum()

Category
Frozen: Frozen Fruit      340
Frozen: Frozen Snacks     161
Pantry: Snacks            737
Produce: Dairy           1098
Produce: Fruit           1346
Produce: Meat             617
Produce: Vegetable        558
Name: Inventory, dtype: int64

In [5]:
df.groupby("Category")["Inventory"].count()

Category
Frozen: Frozen Fruit     2
Frozen: Frozen Snacks    2
Pantry: Snacks           4
Produce: Dairy           4
Produce: Fruit           6
Produce: Meat            3
Produce: Vegetable       4
Name: Inventory, dtype: int64

In [10]:
df[["Category", "Item", "Price_Dollars"]].sort_values("Price_Dollars", ascending=False)

                 Category                   Item  Price_Dollars
23   Frozen: Frozen Fruit     Frozen Blueberries          10.99
11          Produce: Meat      Chicken (Organic)          10.49
10          Produce: Meat                   Beef           8.99
12          Produce: Meat                 Turkey           7.99
24   Frozen: Frozen Fruit       Frozen Pineapple           7.96
21  Frozen: Frozen Snacks        Chicken Nuggets           6.99
5          Produce: Fruit             Watermelon           5.99
19         Pantry: Snacks      Cookies (Oatmeal)           5.39
22  Frozen: Frozen Snacks            Spinach Dip           4.96
15         Produce: Dairy             Milk (Soy)           4.49
2          Produce: Fruit                 Grapes           4.00
4          Produce: Fruit   Organic Strawberries           3.99
13         Produce: Dairy                 Butter           3.50
14         Produce: Dairy                   Eggs           3.29
20         Pantry: Snacks                Raisins           2.99
18         Pantry: Snacks                  Chips           2.50
7      Produce: Vegetable                Carrots           2.00
8      Produce: Vegetable                 Celery           1.99
6      Produce: Vegetable                Cabbage           1.78
17         Pantry: Snacks  Apple Sauce - organic           1.50
0          Produce: Fruit                  Apple           1.50
16         Produce: Dairy                 Yogurt           1.00
3          Produce: Fruit             Grapefruit           0.99
9      Produce: Vegetable               Cucumber           0.99
1          Produce: Fruit                 Banana           0.40